##
## Quality checks
##
name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  code:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: actions/checkout@v4

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
